version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    env_file: ".env"
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_started
        required: true
    networks:
      - nestjs_network
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nestjs_network

volumes:
  mysql-data:
    driver: local
networks:
  nestjs_network:
    driver: bridge
